### ISSUE TITLE
some cities are missed or misspelled

### ISSUE THREAD

**Issue by masoudnemati** [masoudnemati/iran-map#5]
notice that we only need **cities**. so just add cities not villages.

**Comment by IAmTalas** [comment]
Hello @masoudnemati
ill be very happy to resolve this issue
just in case I don't miss something
you mean "شهر" or "شهرستان" ? or both?

**Comment by masoudnemati** [comment]
Hi @IAmTalas , I only need شهرستان for every province. please create **another file** in `src/data` folder, name it `cities2.json` and put your data in that file.
